AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Numpy Lambda
  
  Provided by AWSLambdas.com

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: lambda
  NumpyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - PASTE HERE YOUR LAYER ARN
      Events:
        Numpy:
          Type: Api
          Properties:
            Path: /numpy
            Method: get
            RestApiId: !Ref ApiGateway

Outputs:
  NumpyApi:
    Description: "API URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/lambda/numpy/"
  NumpyFunction:
    Description: "Numpy Lambda Function ARN"
    Value: !GetAtt NumpyFunction.Arn
  NumpyFunctionIamRole:
    Description: "Implicit IAM Role created for the Numpy Lambda"
    Value: !GetAtt NumpyFunctionRole.Arn
